# Generated by Django 4.0.5 on 2024-12-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
    ]
